name: CI

on:
  push:
    branches: [ develop_ ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ui
      uses: docker/build-push-action@v1
      with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./dockerfiles/dockerfile-ui
          repository: ${{ secrets.DOCKER_REPOSITORY_UI }}
          tags: 1.0.0